language: python
python:
  - "3.5"

install:
  - pip install . pytest pytest-coverage coveralls
  - pip install flake8 flake8-import-order pylint

script:
  - py.test --cov=pushwoosh
  - flake8
  - pylint pushwoosh

after_success:
  - coveralls
